using System;

namespace Project_Euler.Even_Fibonacci_Numbers
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(runFibonacciSequence(4000000));

            // An interesting property of Fibonacci numbers discovered from this program:
            // Every third Fibonacci number is even (At least up to 4 million)

            Console.ReadKey();
        }

        static int runFibonacciSequence(int maxNumber)
        {
            var evenFibonacciSum = 0;

            // Initializing the first 2 fibonacci numbers;
            var number1 = 1;
            var number2 = 2;

            while (number2 < maxNumber)
            {
                // Doing the fibonacchi addition
                var fibonacciSum = number2 + number1;

                Console.WriteLine($"{number1} + {number2} = {fibonacciSum}");

                // Determining if the second Fibonacci number is even
                if (number2 % 2 == 0)
                {
                    // If so, add it to the sum.
                    Console.WriteLine($"Even fibonacchi number detected: {number2}");
                    evenFibonacciSum += number2;
                }

                // Reassigning the Fibonacci numbers for the next addition step
                number1 = number2;
                number2 = fibonacciSum;
            }

            return evenFibonacciSum;
        }
    }
}
